# Site settings
title: *folio
email: azhar.murzaeva@bil.omu.edu.tr
baseurl:  ~
url:  ~
twitter_username: ~
github_username:  msAzhar

# Build settings
markdown: kramdown


# Gems
gems: [jekyll-paginate]

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"

collections:
  poetry:
    output: true
    permalink: /poetry/:path/
  folios:
    output: true
    permalink: /folios/:path/

  


