---
author: ms Azhar
description: Фолио
email: azhar.murzaeva@bil.omu.edu.tr
url: www.omu.edu.tr
domain: www.omu.edu.tr
brand: '19'
intro: ''
googleanalytics: ''
googleplus: ''
landslide: /usr/bin/landslide
css: _/default.css _/local.css
js: _/default.js
